micronaut:
    application:
        name: pg-example
    server:
        port: 7777

postgres:
    reactive:
        client:
            port: 5432
            host: localhost
            database: postgres
            user: postgres
            password: example
            maxSize: 5
